src/Entity/Vehicle.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\VehicleRepository")
 * @ORM\HasLifecycleCallbacks
 */
class Vehicle
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Model")
     * @ORM\JoinColumn(nullable=false)
     * @Assert\NotBlank()
     */
    private $model;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="vehicles")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank()
     * @Assert\Range(min="0")
     */
    private $powerKw;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\TransmissionType")
     * @ORM\JoinColumn(nullable=false)
     * @Assert\NotBlank()
     */
    private $transmissionType;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\FuelType")
     * @ORM\JoinColumn(nullable=false)
     * @Assert\NotBlank()
     */
    private $fuelType;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank()
     * @Assert\Range(min="0")
     */
    private $engineCapacity;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank()
     * @Assert\Range(min="1500")
     */
    private $yearMade;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank()
     * @Assert\Range(min="1", max="12")
     */
    private $monthMade;

    /**
     * @ORM\Column(type="datetime")
     */
    private $dateCreated;

    /**
     * @ORM\Column(type="datetime")
     */
    private $dateUpdated;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Visit", mappedBy="vehicle")
     */
    private $visits;

    public function __construct()
    {
        $this->visits = new ArrayCollection();
    }

    public function getId()
    {
        return $this->id;
    }

    public function getModel(): ?Model
    {
        return $this->model;
    }

    public function setModel(?Model $model): self
    {
        $this->model = $model;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getPowerKw(): ?int
    {
        return $this->powerKw;
    }

    public function setPowerKw(int $powerKw): self
    {
        $this->powerKw = $powerKw;

        return $this;
    }

    public function getTransmissionType(): ?TransmissionType
    {
        return $this->transmissionType;
    }

    public function setTransmissionType(?TransmissionType $transmissionType): self
    {
        $this->transmissionType = $transmissionType;

        return $this;
    }

    public function getFuelType(): ?FuelType
    {
        return $this->fuelType;
    }

    public function setFuelType(?FuelType $fuelType): self
    {
        $this->fuelType = $fuelType;

        return $this;
    }

    public function getEngineCapacity(): ?int
    {
        return $this->engineCapacity;
    }

    public function setEngineCapacity(int $engineCapacity): self
    {
        $this->engineCapacity = $engineCapacity;

        return $this;
    }

    public function getYearMade(): ?int
    {
        return $this->yearMade;
    }

    public function setYearMade(int $yearMade): self
    {
        $this->yearMade = $yearMade;

        return $this;
    }

    public function getMonthMade(): ?int
    {
        return $this->monthMade;
    }

    public function setMonthMade(int $monthMade): self
    {
        $this->monthMade = $monthMade;

        return $this;
    }

    public function getDateCreated(): ?\DateTimeInterface
    {
        return $this->dateCreated;
    }

    public function setDateCreated(\DateTimeInterface $dateCreated): self
    {
        $this->dateCreated = $dateCreated;

        return $this;
    }

    public function getDateUpdated(): ?\DateTimeInterface
    {
        return $this->dateUpdated;
    }

    public function setDateUpdated(\DateTimeInterface $dateUpdated): self
    {
        $this->dateUpdated = $dateUpdated;

        return $this;
    }

    /**
     * @return float|int
     */
    public function getLiterCapacity()
    {
        return $this->getEngineCapacity() / 1000;
    }

    /**
     * @return Collection|Visit[]
     */
    public function getVisits(): Collection
    {
        return $this->visits;
    }

    public function addVisit(Visit $visit): self
    {
        if (!$this->visits->contains($visit)) {
            $this->visits[] = $visit;
            $visit->setVehicle($this);
        }

        return $this;
    }

    public function removeVisit(Visit $visit): self
    {
        if ($this->visits->contains($visit)) {
            $this->visits->removeElement($visit);
            // set the owning side to null (unless already changed)
            if ($visit->getVehicle() === $this) {
                $visit->setVehicle(null);
            }
        }

        return $this;
    }

    /**
     * @ORM\PreUpdate
     */
    public function preUpdate()
    {
        $this->setDateUpdated(new \DateTime('now'));
    }

    /**
     * @ORM\PrePersist
     */
    public function prePersist()
    {
        $this->setDateCreated(new \DateTime('now'))
            ->setDateUpdated(new \DateTime('now'));
    }

    /**
     * @return string
     */
    public function __toString()
    {
        return sprintf('%s %s l', $this->getModel(), $this->getLiterCapacity());
    }
}

src/Entity/Vehicles.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\VehiclesRepository")
 */
class Vehicles
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Models")
     * @ORM\JoinColumn(nullable=false)
     */
    private $model_id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user_id;

    /**
     * @ORM\Column(type="integer")
     */
    private $power_kw;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\TransmitionTypes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $transmition_type_id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\FuelTypes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $fuel_type_id;

    /**
     * @ORM\Column(type="integer")
     */
    private $engine_capacity;

    /**
     * @ORM\Column(type="integer")
     */
    private $year_made;

    /**
     * @ORM\Column(type="integer")
     */
    private $month_made;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_created;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_modified;

    public function getId()
    {
        return $this->id;
    }

    public function getModelId(): ?Models
    {
        return $this->model_id;
    }

    public function setModelId(?Models $model_id): self
    {
        $this->model_id = $model_id;

        return $this;
    }

    public function getUserId(): ?User
    {
        return $this->user_id;
    }

    public function setUserId(?User $user_id): self
    {
        $this->user_id = $user_id;

        return $this;
    }

    public function getPowerKw(): ?int
    {
        return $this->power_kw;
    }

    public function setPowerKw(int $power_kw): self
    {
        $this->power_kw = $power_kw;

        return $this;
    }

    public function getTransmitionTypeId(): ?TransmitionTypes
    {
        return $this->transmition_type_id;
    }

    public function setTransmitionTypeId(?TransmitionTypes $transmition_type_id): self
    {
        $this->transmition_type_id = $transmition_type_id;

        return $this;
    }

    public function getFuelTypeId(): ?FuelTypes
    {
        return $this->fuel_type_id;
    }

    public function setFuelTypeId(?FuelTypes $fuel_type_id): self
    {
        $this->fuel_type_id = $fuel_type_id;

        return $this;
    }

    public function getEngineCapacity(): ?int
    {
        return $this->engine_capacity;
    }

    public function setEngineCapacity(int $engine_capacity): self
    {
        $this->engine_capacity = $engine_capacity;

        return $this;
    }

    public function getYearMade(): ?int
    {
        return $this->year_made;
    }

    public function setYearMade(int $year_made): self
    {
        $this->year_made = $year_made;

        return $this;
    }

    public function getMonthMade(): ?int
    {
        return $this->month_made;
    }

    public function setMonthMade(int $month_made): self
    {
        $this->month_made = $month_made;

        return $this;
    }

    public function getDateCreated(): ?\DateTimeInterface
    {
        return $this->date_created;
    }

    public function setDateCreated(\DateTimeInterface $date_created): self
    {
        $this->date_created = $date_created;

        return $this;
    }

    public function getDateModified(): ?\DateTimeInterface
    {
        return $this->date_modified;
    }

    public function setDateModified(\DateTimeInterface $date_modified): self
    {
        $this->date_modified = $date_modified;

        return $this;
    }
}

src/Form/VehicleType.php
<?php

namespace App\Form;

use App\Entity\Model;
use App\Entity\User;
use App\Entity\Vehicle;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormError;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface;

class VehicleType extends AbstractType
{
    /**
     * @var TokenStorageInterface
     */
    private $tokenStorage;

    /**
     * @var int
     */
    private $maxUserVehicleCount;

    public function __construct(TokenStorageInterface $tokenStorage, $maxUserVehicleCount)
    {
        $this->tokenStorage = $tokenStorage;
        $this->maxUserVehicleCount = $maxUserVehicleCount;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('powerKw')
            ->add('engineCapacity')
            ->add('yearMade')
            ->add('monthMade')

            ->add('model', EntityType::class,
                [
                    'class' => Model::class,
//                    'label' => 'address.city',
//                    'empty_data' => 'address.please_select',
//                    'query_builder' => function (ModelRepository $er) us) {
//                        return $er->createQueryBuilder('c')->orderBy('c.name', 'ASC');
//                    },
                    'group_by' => function(Model $value, $key, $index) {
                        return $value->getManufacturer()->getName();
                    }
                ])
            ->add('transmissionType')
            ->add('fuelType');

        $builder->addEventListener(FormEvents::PRE_SUBMIT, [$this, 'preSubmit']);

        //TODO: Add manufacturer field to filter out models
//        $builder->addEventListener(FormEvents::PRE_SET_DATA, [$this, 'preSetData']);
//        $builder->get('manufacturer')->addEventListener(FormEvents::POST_SUBMIT, [$this, 'postSubmitManufacturer']);

    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Vehicle::class,
        ]);
    }

    /**
     * @param FormEvent $event
     */
    public function preSubmit(FormEvent $event)
    {
        /** @var User $user */
        $user = $this->tokenStorage->getToken()->getUser();

        if ($user && $user->getVehicles()->count() >= $this->maxUserVehicleCount) {
            $event->getForm()
                ->addError(
                    new FormError(sprintf('vehicle.form.max_vehicle_error %s', $this->maxUserVehicleCount))
                );
        }
    }

//    /**
//     * @param FormEvent $event
//     */
//    public function preSetData(FormEvent $event)
//    {
//        $this->getModelSelections($event->getForm(), $event->getData()->getManufacturer());
//    }
//
//    /**
//     * @param FormEvent $event
//     */
//    public function postSubmitManufacturer(FormEvent $event)
//    {
//        $form = $event->getForm();
//        $this->getModelSelections($form->getParent(), $form->getData());
//    }
//
//    /**
//     * @param FormInterface $form
//     * @param Manufacturer|null $manufacturer
//     */
//    private function getModelSelections(FormInterface $form, Manufacturer $manufacturer = null)
//    {
//        $models = $manufacturer ? $manufacturer->getModels() : [];
//        $form->add('model', EntityType::class, [
//           'class' => 'App\Entity\Model',
//            'placeholder' => '',
//            'choices' => $models,
//        ]);
//    }
}

src/Controller/VehicleController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Entity\Vehicle;
use App\Form\VehicleType;
use App\Repository\VisitRepository;
use App\Security\VehicleVoter;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/vehicle")
 * @Security("has_role('ROLE_USER')")
 */
class VehicleController extends Controller
{
    /**
     * @Route("/", name="vehicle_index", methods="GET")
     */
    public function index(): Response
    {
        /** @var User $user */
        $user = $this->get('security.token_storage')->getToken()->getUser();

        return $this->render('vehicle/index.html.twig', ['vehicles' => $user->getVehicles()]);
    }

    /**
     * @Route("/new", name="vehicle_new", methods="GET|POST")
     */
    public function new(Request $request): Response
    {
        $vehicle = new Vehicle();
        $form = $this->createForm(VehicleType::class, $vehicle);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $vehicle->setUser($this->get('security.token_storage')->getToken()->getUser());
            $em = $this->getDoctrine()->getManager();
            $em->persist($vehicle);
            $em->flush();

            return $this->redirectToRoute('vehicle_index');
        }

        return $this->render('vehicle/new.html.twig', [
            'vehicle' => $vehicle,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="vehicle_show", methods="GET")
     */
    public function show(Vehicle $vehicle): Response
    {
        $this->denyAccessUnlessGranted(VehicleVoter::VIEW, $vehicle);

        return $this->render('vehicle/show.html.twig', ['vehicle' => $vehicle]);
    }

    /**
     * @Route("/{id}/edit", name="vehicle_edit", methods="GET|POST")
     */
    public function edit(Request $request, Vehicle $vehicle): Response
    {
        $this->denyAccessUnlessGranted(VehicleVoter::EDIT, $vehicle);

        $form = $this->createForm(VehicleType::class, $vehicle);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('vehicle_edit', ['id' => $vehicle->getId()]);
        }

        return $this->render('vehicle/edit.html.twig', [
            'vehicle' => $vehicle,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="vehicle_delete", methods="DELETE")
     */
    public function delete(Request $request, Vehicle $vehicle, VisitRepository $vs): Response
    {
        $this->denyAccessUnlessGranted(VehicleVoter::DELETE, $vehicle);

        if (count($vs->getUnfinishedVehicleVisits($vehicle)) > 0) {
            $this->addFlash('danger', 'vehicle.delete.has_unfinished_visits');
        } elseif ($this->isCsrfTokenValid('delete'.$vehicle->getId(), $request->request->get('_token'))) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($vehicle);
            $em->flush();
        }

        return $this->redirectToRoute('vehicle_index');
    }
}

templates/vehicle/_delete_form.html.twig
<form method="post" action="{{ path('vehicle_delete', {'id': vehicle.id}) }}" onsubmit="return confirm('{{ 'vehicle.action.confirm_delete'|trans }}');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ vehicle.id) }}">
    <button class="btn">{{ 'vehicle.action.delete'|trans }}</button>
</form>

templates/vehicle/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/vehicle/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'vehicle.edit'|trans }}{% endblock %}

{% block body %}
    <h1>{{ 'vehicle.edit'|trans }}</h1>

    {{ include('vehicle/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('vehicle_index') }}">{{ 'vehicle.action.index'|trans }}</a>

    {{ include('vehicle/_delete_form.html.twig') }}
{% endblock %}

templates/vehicle/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'vehicle.title'|trans }}{% endblock %}

{% block mainHeader %}{{ 'vehicle.title'|trans }}{% endblock  %}
{% block body %}

    <div class="row">
        {% for vehicle in vehicles %}

            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 card">
                <img class="card-img-top" src="{{ asset('images/vehicles/default.jpg') }}" alt="Card image cap">
                <div class="card-body">
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">{{ vehicle.model.manufacturer.name ~ ' ' ~ vehicle.model.name ~ ' ' ~ vehicle.literCapacity }} l</li>
                        <li class="list-group-item">{{ vehicle.powerKw }} kw</li>
                        <li class="list-group-item">{{ vehicle.yearMade ~ '-' ~ "%02d"|format(vehicle.monthMade)}}</li>
                        <li class="list-group-item">
                            {{ 'vehicle.form.date_created'|trans }}
                            {{ vehicle.dateCreated ? vehicle.dateCreated|date('Y-m-d H:i:s') : '' }}
                        </li>
                        <li class="list-group-item">
                            {{ 'vehicle.form.date_updated'|trans }}
                            {{ vehicle.dateUpdated ? vehicle.dateUpdated|date('Y-m-d H:i:s') : '' }}
                        </li>
                        <li class="list-group-item">
                            <a href="{{ path('vehicle_show', {'id': vehicle.id}) }}">{{ 'vehicle.action.show'|trans }}</a>
                            <a href="{{ path('vehicle_edit', {'id': vehicle.id}) }}">{{ 'vehicle.action.edit'|trans }}</a>
                        </li>
                    </ul>
                </div>
            </div>
        {% else %}
            {{ 'vehicle.no'|trans }}
        {% endfor %}
    </div>

    <a href="{{ path('vehicle_new') }}">{{ 'vehicle.action.new'|trans }}</a>
{% endblock %}

templates/vehicle/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'vehicle.new'|trans }}{% endblock %}

{% block mainHeader %}{{ 'vehicle.action.new'|trans }}{% endblock %}
{% block body %}

    {{ include('vehicle/_form.html.twig') }}

    <a href="{{ path('vehicle_index') }}">{{ 'vehicle.action.index'|trans }}</a>
{% endblock %}

templates/vehicle/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'vehicle.title1'|trans }}{% endblock %}

{% block body %}


    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 card">
            <img class="card-img-top" src="{{ asset('images/vehicles/default.jpg') }}" alt="Card image cap">
            <div class="card-body">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">{{ vehicle.model.manufacturer.name ~ ' ' ~ vehicle.model.name ~ ' ' ~ vehicle.literCapacity }} l</li>
                    <li class="list-group-item">{{ vehicle.powerKw }} kw</li>
                    <li class="list-group-item">{{ vehicle.yearMade ~ '-' ~ "%02d"|format(vehicle.monthMade)}}</li>
                    <li class="list-group-item">
                        {{ 'vehicle.form.date_created'|trans }}
                        {{ vehicle.dateCreated ? vehicle.dateCreated|date('Y-m-d H:i:s') : '' }}
                    </li>
                    <li class="list-group-item">
                        {{ 'vehicle.form.date_updated'|trans }}
                        {{ vehicle.dateUpdated ? vehicle.dateUpdated|date('Y-m-d H:i:s') : '' }}
                    </li>
                    <li class="list-group-item">
                        <a href="{{ path('vehicle_index', {'id': vehicle.id}) }}">{{ 'vehicle.action.index'|trans }}</a>
                        <a href="{{ path('vehicle_edit', {'id': vehicle.id}) }}">{{ 'vehicle.action.edit'|trans }}</a>
                    </li>
                    <li class="list-group-item">
                        {{ include('vehicle/_delete_form.html.twig') }}
                    </li>
                </ul>
            </div>
        </div>
    </div>
{% endblock %}